### ISSUE TITLE
Implement Pagination for the API Requests

### ISSUE THREAD

**Issue by vineeth-asml** [asml-actions/github-fork-updater#100]
Number of response is hard coded to 100 which maximum ( default 30 ) [Updater.ps1](https://github.com/asml-actions/github-fork-updater/blob/main/updater.ps1#L27) 
Implement pagination to fix any issue in the feature

**Comment by r-derasari-asml** [comment]
Closed in https://github.com/rajbos/github-fork-updater/pull/82
